name: 图像测试
description: 一种轻量级的 websocket 的客户端。1.CDK：添加工程后，组件里显示不合理yoc7
2.CDK：烧写elf文件流程不合理，最好先添加，而不是等到建立工程后
3.CDK：修改工程名称后，建议文件夹名称联动修改
4.CDK：创建工程后，再次切换工程，默认选择的不要总是alicoap，最好是我上次选择的通道
5.烟感工程天翼云和中移动云编译不过
keywords:
  - zhangyujie
  - 张玉洁的标签
license: MIT                                   # GPLv2，LGPLv2.1，MIT，Apache license v2.0，BSD

source_file:
  - src/*.c
logo: https://www.lua.org/images/lua-logo.gif
build_config:
  include:
    - include
  cflag: ""                             # C 编译器所需要要的编译参数
  define:                                      # 宏定义
    - CONFIG_USING_TLS

install:
  - dest: include
    source:
      - "include/librws.h"
