name: update测试111
description: test
homepage: www.baidu.com
keywords:
source_file:
  - src/*.c
logo: https://b-ssl.duitang.com/uploads/item/201510/21/20151021214935_zLVKC.jpeg
build_config:
  include:
    - include
  cflag: ""                             # C 编译器所需要要的编译参数
  define:                                      # 宏定义
    - CONFIG_USING_TLS

install:
  - dest: include
    source:
      - "include/librws.h"
