name: 主页测试描述和标签
description:
license: MIT                            
homepage: https://www.baidu.com/
source_file:
  - src/*.c
logo: https://www.lua.org/images/lua-logo.gif
build_config:
  include:
    - include
  cflag: ""                             # C 编译器所需要要的编译参数
  define:                                      # 宏定义
    - CONFIG_USING_TLS

install:
  - dest: include
    source:
      - "include/librws.h"
