name: 图像!@#$%^&*(){}|;'<?>
keywords:
  - zhangyujie
  - 张玉洁的标签
license: MIT                                   # GPLv2，LGPLv2.1，MIT，Apache license v2.0，BSD

source_file:
  - src/*.c
logo: https://www.lua.org/images/lua-logo.gif
build_config:
  include:
    - include
  cflag: ""                             # C 编译器所需要要的编译参数
  define:                                      # 宏定义
    - CONFIG_USING_TLS

install:
  - dest: include
    source:
      - "include/librws.h"
