name: update测试222
description: test666
homepage: www.baidu.com
keywords:
source_file:
  - src/*.c
logo: 
build_config:
  include:
    - include
  cflag: ""                             # C 编译器所需要要的编译参数
  define:                                      # 宏定义
    - CONFIG_USING_TLS

install:
  - dest: include
    source:
      - "include/librws.h"
