name: zhangyujieaa
description: 一种轻量级的 websocket 的客户端。1.CDK：添加工程后，组件里显示不合理yoc7
2.CDK：烧写elf文件流程不合理，最好先添加，而不是等到建立工程后
3.CDK：修改工程名称后，建议文件夹名称联动修改
4.CDK：创建工程后，再次切换工程，默认选择的不要总是alicoap，最好是我上次选择的通道
5.烟感工程天翼云和中移动云编译不过
keywords:
  - zhangyujie
  - 张玉洁的标签
license: MIT                                   # GPLv2，LGPLv2.1，MIT，Apache license v2.0，BSD

source_file:
  - src/*.c
logo：http://image.baidu.com/search/detail?ct=503316480&z=0&ipn=false&word=%E6%9D%8E%E6%98%93%E5%B3%B0&step_word=&hs=0&pn=1&spn=0&di=61490&pi=0&rn=1&tn=baiduimagedetail&is=0%2C0&istype=0&ie=utf-8&oe=utf-8&in=&cl=2&lm=-1&st=undefined&cs=668515561%2C3337529090&os=1795854278%2C1003247339&simid=4053682836%2C333459273&adpicid=0&lpn=0&ln=2110&fr=&fmq=1565246143989_R&fm=&ic=undefined&s=undefined&hd=undefined&latest=undefined&copyright=undefined&se=&sme=&tab=0&width=&height=&face=undefined&ist=&jit=&cg=star&bdtype=0&oriquery=&objurl=http%3A%2F%2Fimg3.duitang.com%2Fuploads%2Fitem%2F201605%2F06%2F20160506152334_5TVHr.thumb.700_0.jpeg&fromurl=ippr_z2C%24qAzdH3FAzdH3Fooo_z%26e3B17tpwg2_z%26e3Bv54AzdH3Fks52AzdH3F%3Ft1%3Dc08dclbc0&gsm=0&rpstart=0&rpnum=0&islist=&querylist=

build_config:
  include:
    - include
  cflag: ""                             # C 编译器所需要要的编译参数
  define:                                      # 宏定义
    - CONFIG_USING_TLS

install:
  - dest: include
    source:
      - "include/librws.h"
